DROP TABLE BIN CASCADE CONSTRAINTS ;

DROP TABLE BIN_CONTRACT CASCADE CONSTRAINTS ;

DROP TABLE BIN_REQUEST CASCADE CONSTRAINTS ;

DROP TABLE BIN_TYPE CASCADE CONSTRAINTS ;

DROP TABLE COL_CONTRACT CASCADE CONSTRAINTS ;

DROP TABLE CONTRACT CASCADE CONSTRAINTS ;

DROP TABLE COUNCIL CASCADE CONSTRAINTS ;

DROP TABLE DRIVER CASCADE CONSTRAINTS ;

DROP TABLE INVOICE CASCADE CONSTRAINTS ;

DROP TABLE PROPERTY CASCADE CONSTRAINTS ;

DROP TABLE SCHEDULE CASCADE CONSTRAINTS ;

DROP TABLE TRUCK CASCADE CONSTRAINTS ;